script(PS): add MicrosoftGraph
dlw-digitalworkplace/dw-script-lib pull request #18
Opened 2023-11-14 13:48 UTC by PieterHeemeryck

2023-11-27 07:27 UTC, agtenr requested changes

2023-11-27 07:27 UTC, agtenr commented on PowerShell/MicrosoftGraph/MicrosoftGraph.md
> +## Prerequisites
The Microsoft.Graph module is required I guess?

2023-11-27 07:27 UTC, agtenr commented on PowerShell/MicrosoftGraph/MicrosoftGraph.ps1
Nice Examples Pieter. Maybe just change the name to follow the naming conventions. (e.g. Explore-MicrosoftGraphModule ?)

2023-12-05 15:42 UTC, PieterHeemeryck commented on PowerShell/MicrosoftGraph/MicrosoftGraph.md
> +## Prerequisites
@agtenr Fixed

2023-12-05 15:42 UTC, PieterHeemeryck commented on PowerShell/MicrosoftGraph/MicrosoftGraph.ps1
@agtenr Fixed

2023-12-15 15:56 UTC, agtenr approved these changes

2023-12-15 15:56 UTC, agtenr commented on PowerShell/MicrosoftGraph/MicrosoftGraph.ps1
Thanks. Nice addition

2023-12-15 15:56 UTC, merged